# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnifiDoorbellChime < Formula
  desc "Notify to Mac when Doorbell rung."
  homepage "https://github.com/sawadashota/unifi-doorbell-chime"
  version "0.1.13"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sawadashota/unifi-doorbell-chime/releases/download/v0.1.13/unifi-doorbell-chime_v0.1.13_darwin_amd64.tar.gz"
    sha256 "bad30f920c9c02fa2e2c5e05ff8b7f9f5e2a9923f9d64af9d3359bcee05b41a0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sawadashota/unifi-doorbell-chime/releases/download/v0.1.13/unifi-doorbell-chime_v0.1.13_linux_amd64.tar.gz"
    sha256 "fd59a47ffdd4789871da14703e813524863b4e129e8d9969c985b84fe0ba118c"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/sawadashota/unifi-doorbell-chime/releases/download/v0.1.13/unifi-doorbell-chime_v0.1.13_linux_arm.tar.gz"
    sha256 "d2b42ce730fcc40f561bdcfce479fd3da3243e2d966ede6384b21e32568797b7"
  end

  def install
    bin.install "unifi-doorbell-chime"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{opt_bin}/unifi-doorbell-chime</string>
      <string>start</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/unifi-doorbell-chime.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/unifi-doorbell-chime.log</string>
  </dict>
</plist>

  EOS
  end

  test do
    system "#{bin}/unifi-doorbell-chime --version"
  end
end
