# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnifiDoorbellNotifier < Formula
  desc "Notify to your PC when Doorbell rung."
  homepage "https://github.com/sawadashota/unifi-doorbell-notifier"
  version "0.1.1"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sawadashota/unifi-doorbell-notifier/releases/download/v0.1.1/unifi-doorbell-notifier_v0.1.1_x86_64-apple-darwin.zip"
    sha256 "46e8e34b834e73e72efc7ec4e81a0828682e839ae85fb18c8e288d3bdcd3ad16"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sawadashota/unifi-doorbell-notifier/releases/download/v0.1.1/unifi-doorbell-notifier_v0.1.1_x86_64-unknown-linux-musl.tar.gz"
    sha256 "46cb13073f0b3731cb8d6e72da3272b0cf4ed205c0a9f9d0e9dcfbb51f4de3a1"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/sawadashota/unifi-doorbell-notifier/releases/download/v0.1.1/unifi-doorbell-notifier_v0.1.1_x86_64-unknown-linux-musl.tar.gz"
    sha256 "46cb13073f0b3731cb8d6e72da3272b0cf4ed205c0a9f9d0e9dcfbb51f4de3a1"
  end

  def install
    bin.install "unifi-doorbell-notifier"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{opt_bin}/unifi-doorbell-notifier</string>
      <string>serve</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/unifi-doorbell-notifier.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/unifi-doorbell-notifier.log</string>
  </dict>
</plist>

  EOS
  end

  test do
    system "#{bin}/unifi-doorbell-notifier --version"
  end
end
